# Generated by Django 3.1.2 on 2020-10-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201017_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Post',
        ),
    ]
